// -*- mode: js2; indent-tabs-mode: nil; js2-basic-offset: 4 -*-
// vim:fdm=syntax
// by:hollowman6@github tuberry@github

"use strict";

var Fields = {
  ASCIIMODE: "ascii-mode",
  CUSTOMFONT: "custom-font",
  CUSTOMBG: "custom-bg",
  CUSTOMBGDARK: "custom-bg-dark",
  INPUTONLIST: "input-on-list",
  INPUTOFFLIST: "input-off-list",
  CUSTOMTHEME: "custom-theme",
  ENABLECUSTOMTHEME: "enable-custom-theme",
  CUSTOMTHEMENIGHT: "custom-theme-dark",
  ENABLECUSTOMTHEMENIGHT: "enable-custom-theme-dark",
  INPUTLIST: "input-mode-list",
  REMEMBERINPUT: "input-mode-remember",
  USECUSTOMFONT: "use-custom-font",
  USECUSTOMBG: "use-custom-bg",
  USECUSTOMBGDARK: "use-custom-bg-dark",
  AUTOSWITCH: "enable-auto-switch",
  ENABLEORIEN: "enable-orientation",
  UNKNOWNSTATE: "unkown-ascii-state",
  ORIENTATION: "candidate-orientation",
  BGMODE: "custom-bg-mode",
  BGDARKMODE: "custom-bg-dark-mode",
  BGREPEATMODE: "custom-bg-repeat-mode",
  BGDARKREPEATMODE: "custom-bg-dark-repeat-mode",
  MENUIBUSEMOJI: "menu-ibus-emoji",
  MENUEXTPREF: "menu-extension-preference",
  MENUIBUSPREF: "menu-ibus-preference",
  MENUIBUSVER: "menu-ibus-version",
  MENUIBUSREST: "menu-ibus-restart",
  MENUIBUSEXIT: "menu-ibus-exit",
  IBUSRESTTIME: "ibus-restart-time",
  USEINPUTIND: "use-input-indicator",
  INPUTINDTOG: "input-indicator-only-on-toggle",
  INPUTINDASCII: "input-indicator-only-use-ascii",
  INPUTINDANIM: "input-indicator-animation",
  USEINDAUTOHID: "use-indicator-auto-hide",
  INPUTINDHID: "input-indicator-hide-time",
  INPUTINDRIGC: "input-indicator-right-close",
  USECANDANIM: "use-popup-animation",
  CANDANIMATION: "candidate-popup-animation",
  USEREPOSITION: "use-candidate-reposition",
  USEINPUTINDLCLK: "use-indicator-left-click",
  INPUTINDLCLICK: "indicator-left-click-func",
  USETRAY: "use-tray",
  USETRAYSSWITCH: "use-tray-click-source-switch",
  TRAYSSWITCHKEY: "tray-source-switch-click-key",
  USECANDRIGHTSWITCH: "use-candidate-box-right-click",
  CANDRIGHTFUNC: "candidate-box-right-click-func",
  USECANDSTILL: "use-candidate-still",
  CANDSTILLPOS: "candidate-still-position",
  REMCANDPOS: "remember-candidate-position",
  CANDBOXPOS: "candidate-box-position",
};
